version: '3.1'
services:
  apache:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    networks:
      internal:
        #ipv4_address: 172.18.0.2
    ports:
      - 8080:80
  mysql:
    build:
      context: .
      dockerfile: ./bdd/Dockerfile
    networks:
      internal:
        #ipv4_address: 172.18.0.3
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
networks:
  internal:
    #driver: bridge
    #internal: true
    #ipam:
      #driver: default
      #config:
        #- subnet: 172.18.0.0/16